= Couchbase Cluster using Docker

Build the image (only for dev, otherwise already available in Docker Hub):

```console
docker build -t arungupta/couchbase-node .
```

== How to setup cluster

=== Start Consul

. Create a machine for Consul:

  docker-machine create -d=virtualbox consul-machine

. Connect to this Machine:

  eval $(docker-machine env consul-machine)

. Use http://github.com/arun-gupta/docker-images/blob/master/consul/docker-compose.yml[Docker Compose for Consul] and start Consul:

  docker-compose up -d

=== Create Docker Swarm Cluster

. Create master:

  docker-machine create -d virtualbox --virtualbox-disk-size "5000" --swarm --swarm-master --swarm-discovery="consul://$(docker-machine ip consul-machine):8500" --engine-opt="cluster-store=consul://$(docker-machine ip consul-machine):8500" --engine-opt="cluster-advertise=eth1:2376" swarm-master

. Create node-01:

  docker-machine create -d virtualbox --virtualbox-disk-size "5000" --swarm --swarm-discovery="consul://$(docker-machine ip consul-machine):8500" --engine-opt="cluster-store=consul://$(docker-machine ip consul-machine):8500" --engine-opt="cluster-advertise=eth1:2376" swarm-node-01

. Create node-02:

  docker-machine create -d virtualbox --virtualbox-disk-size "5000" --swarm --swarm-discovery="consul://$(docker-machine ip consul-machine):8500" --engine-opt="cluster-store=consul://$(docker-machine ip consul-machine):8500" --engine-opt="cluster-advertise=eth1:2376" swarm-node-02

. Connect to Swarm:

  eval "$(docker-machine env --swarm swarm-master)"

. Use Compose file from link:docker-compose.yml[], and run three instances of container:

  docker-compose up -d
  docker-compose scale db=2

. Check the Couchbase containers on Swarm:
+
[source, text]
----
docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED              STATUS              PORTS                                                                                                                                            NAMES
08e3af15466f        arungupta/couchbase-node   "/entrypoint.sh /opt/"   36 seconds ago       Up 35 seconds       192.168.99.105:4369->4369/tcp, 192.168.99.105:8091-8093->8091-8093/tcp, 11207/tcp, 11211/tcp, 192.168.99.105:11210->11210/tcp, 18091-18092/tcp   swarm-node-02/couchbasenode_db_2
6b8704a43e99        arungupta/couchbase-node   "/entrypoint.sh /opt/"   About a minute ago   Up About a minute   192.168.99.104:4369->4369/tcp, 192.168.99.104:8091-8093->8091-8093/tcp, 11207/tcp, 11211/tcp, 192.168.99.104:11210->11210/tcp, 18091-18092/tcp   swarm-node-01/couchbasenode_db_1
----
+
. Get IP address of all the Machines:

  docker inspect --format '{{ .Node.IP }}' $(docker ps -q)

. Create the cluster:

  curl -X POST -u Administrator:password http://192.168.99.104:8091/controller/addNode -d hostname=192.168.99.105 -d user=Administrator -d password=password -d services=kv,n1ql,index
  {"otpNode":"ns_1@172.17.0.4"}
  
  BROKEN HERE
  
. Rebalance the cluster:
+
[source, text]
----
curl -v -X POST -u Administrator:password http://172.17.0.3:8091/controller/rebalance --data 'knownNodes=ns_1%40172.17.0.3%2Cns_1%40172.17.0.4 %2Cns_1%40172.17.0.5&ejectedNodes='
* About to connect() to 172.17.0.3 port 8091 (#0)
*   Trying 172.17.0.3...
* Adding handle: conn: 0xb213c0
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0xb213c0) send_pipe: 1, recv_pipe: 0
* Connected to 172.17.0.3 (172.17.0.3) port 8091 (#0)
* Server auth using Basic with user 'Administrator'
> POST /controller/rebalance HTTP/1.1
> Authorization: Basic QWRtaW5pc3RyYXRvcjpwYXNzd29yZA==
> User-Agent: curl/7.33.0
> Host: 172.17.0.3:8091
> Accept: */*
> Content-Length: 82
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 82 out of 82 bytes
< HTTP/1.1 200 OK
* Server Couchbase Server is not blacklisted
< Server: Couchbase Server
< Pragma: no-cache
< Date: Tue, 22 Dec 2015 00:32:38 GMT
< Content-Length: 0
< Cache-Control: no-cache
<
* Connection #0 to host 172.17.0.3 left intact
----

Questions:

. 8091 and 8093 ports need to be exposed in order for the application to access the cluster. It can be from one container, ideally all of them. What do you recommend so that there is no port conflict?
. How do I ensure that only one instance of Couchbase container is started on Docker Swarm node? Scheduling strategy?
. Are there any pre/post scripts that can be automatically run after Compose scaling? Otherwise scaling would always require manual script invocation.
. How do other databases scale, e.g. MySQL? Any existing recipes?


