FROM arungupta/wildfly-centos
#FROM centos/wildfly
MAINTAINER Arun Gupta <arungupta@redhat.com>

RUN curl -L https://github.com/javaee-samples/javaee7-hol/raw/master/solution/movieplex7-1.0-SNAPSHOT.war -o /opt/jboss/wildfly/standalone/deployments/movieplex7-1.0-SNAPSHOT.war
